CREATE TABLE TEST_ENTITY
(
    ENTITY_ID NUMBER,
    ENTITY_NAME VARCHAR(100),
    STATUS VARCHAR(10),
    CREATED_DATE DATE
);

CREATE TABLE TEST_ACCOUNT
(
    ACCOUNT_ID NUMBER,
    ENTITY_ID NUMBER,
    TYPE VARCHAR(10),
    VALUE NUMBER,
    CREATED_DATE DATE
);

CREATE TABLE TEST_STATUS
(
    ACCOUNT_ID NUMBER,
    STATUS_CODE VARCHAR(10),
    ACTIVE_FLAG VARCHAR(1)
);

CREATE TABLE TEST_HISTORY
(
    ACCOUNT_ID NUMBER,
    CHANGE_DATE DATE,
    FLAG VARCHAR(1)
);