INSERT INTO TEST_ENTITY
SELECT
    LEVEL,
    'ENTITY_'||LEVEL,
    CASE WHEN MOD(LEVEL,2)=0 THEN 'ACTIVE' ELSE 'INACTIVE' END,
    SYSDATE - MOD(LEVEL,100)
FROM DUAL
CONNECT BY LEVEL < 10000;

INSERT INTO TEST_ACCOUNT
SELECT
    LEVEL,
    MOD(LEVEL,5000)+1,
    CASE WHEN MOD(LEVEL,3)=0 THEN 'A' ELSE 'B' END,
    DBMS_RANDOM.VALUE(1,10000),
    SYSDATE
FROM DUAL
CONNECT BY LEVEL < 20000;

COMMIT;