SET TIMING ON

WITH BASE AS
(
SELECT
    E.ENTITY_ID,
    E.ENTITY_NAME,
    E.STATUS,
    A.ACCOUNT_ID,
    A.VALUE,
    S.STATUS_CODE
FROM TEST_ENTITY E
JOIN TEST_ACCOUNT A
    ON E.ENTITY_ID = A.ENTITY_ID
JOIN TEST_STATUS S
    ON A.ACCOUNT_ID = S.ACCOUNT_ID
WHERE E.STATUS = 'ACTIVE'
)

SELECT
ROW_NUMBER() OVER(ORDER BY ACCOUNT_ID) RN,
ENTITY_ID,
ENTITY_NAME,
GET_SAMPLE_NAME(ENTITY_ID) ENTITY_LABEL,
ACCOUNT_ID,
VALUE,
GET_STATUS_NAME(STATUS_CODE) STATUS_NAME
FROM BASE;